### ISSUE TITLE
When will full preprocessing code be released?

### ISSUE THREAD

**Issue by dogydev** [cooelf/SG-Net#2]

**Comment by ll906875341** [comment]
I have the same problem, I hope the author can releas the full preprocessing code as soon as possible

**Comment by CoyoteLeo** [comment]
I have the same problem

**Comment by felipenunezb** [comment]
did anyone find out how to create the additional file?
I was able to use the HPSG Neural Parser, got the heads and the types, but I have no clue on how hpsg_list_??? data is created. 

Any hints?

**Comment by cooelf** [comment]
Hi, the convert script has been uploaded.

**Comment by cpmss521** [comment]
what's the mean of hpsg_lists_ que ? @cooelf
